\section{Socket\-Exception Class Reference}
\label{classSocketException}\index{SocketException@{SocketException}}
{\tt \#include $<$Practical\-Socket.h$>$}

\subsection*{Public Member Functions}
\begin{CompactItemize}
\item 
{\bf Socket\-Exception} (const string \&message, bool incl\-Sys\-Msg=false)  throw ()
\item 
{\bf $\sim$Socket\-Exception} ()  throw ()
\item 
const char $\ast$ {\bf what} () const  throw ()
\end{CompactItemize}
\subsection*{Private Attributes}
\begin{CompactItemize}
\item 
string {\bf user\-Message}
\end{CompactItemize}


\subsection{Detailed Description}
Signals a problem with the execution of a socket call. 



\subsection{Constructor \& Destructor Documentation}
\index{SocketException@{Socket\-Exception}!SocketException@{SocketException}}
\index{SocketException@{SocketException}!SocketException@{Socket\-Exception}}
\subsubsection{\setlength{\rightskip}{0pt plus 5cm}Socket\-Exception::Socket\-Exception (const string \& {\em message}, bool {\em incl\-Sys\-Msg} = {\tt false})  throw ()}\label{classSocketException_bb5bcecd9d9e20868c237ec5a82cf5c3}


Construct a \doxyref{Socket\-Exception}{p.}{classSocketException} with a explanatory message. \begin{Desc}
\item[Parameters:]
\begin{description}
\item[{\em message}]explanatory message \item[{\em inc\-Sys\-Msg}]true if system message (from strerror(errno)) should be postfixed to the user provided message \end{description}
\end{Desc}
\index{SocketException@{Socket\-Exception}!~SocketException@{$\sim$SocketException}}
\index{~SocketException@{$\sim$SocketException}!SocketException@{Socket\-Exception}}
\subsubsection{\setlength{\rightskip}{0pt plus 5cm}Socket\-Exception::$\sim$Socket\-Exception ()  throw ()}\label{classSocketException_659557c899329aea01977c980c4db9b9}


Provided just to guarantee that no exceptions are thrown. 

\subsection{Member Function Documentation}
\index{SocketException@{Socket\-Exception}!what@{what}}
\index{what@{what}!SocketException@{Socket\-Exception}}
\subsubsection{\setlength{\rightskip}{0pt plus 5cm}const char $\ast$ Socket\-Exception::what () const  throw ()}\label{classSocketException_534b0625abe62cad2bae94758aa6eb42}


Get the exception message \begin{Desc}
\item[Returns:]exception message \end{Desc}


\subsection{Member Data Documentation}
\index{SocketException@{Socket\-Exception}!userMessage@{userMessage}}
\index{userMessage@{userMessage}!SocketException@{Socket\-Exception}}
\subsubsection{\setlength{\rightskip}{0pt plus 5cm}string {\bf Socket\-Exception::user\-Message}\hspace{0.3cm}{\tt  [private]}}\label{classSocketException_dcfeba6d4ce5754b48ae9d37b07a7e87}




The documentation for this class was generated from the following files:\begin{CompactItemize}
\item 
{\bf Practical\-Socket.h}\item 
{\bf Practical\-Socket.cpp}\end{CompactItemize}
